from classes import category, category_product_range, order
from classes import non_positive_prd_quantity_exception

Category = category.Category
CategoryProductRange = category_product_range.CategoryProductRange
Order = order.Order
NonPositiveProductQuantityException = non_positive_prd_quantity_exception.NonPositiveProductQuantityException
